<?php
/**
*应用入口文件
*/
session_start();
define('IN_GALAVY',true);//入口标识
define('GALAVY_DEBUG',true);//调试模式true打开,false关闭
define('GALAVY_TIMEZONE','Asia/ShangHai');//时区
header("Content-type:text/html;charset=UTF-8");//编码
define('ROOT',dirname(dirname(dirname(dirname(__FILE__)))));//根目录
define('APP_ROOT',dirname(dirname(dirname(__FILE__))));//应用根目录
define('APP_NAME','appname');//应用名字
define('APP_PATH',APP_ROOT.(APP_NAME?"/".APP_NAME:""));//应用目录
define('GALAVY_PATH',ROOT.'/lib/galavy');//galavy类库目录
define('DAO_PATH',ROOT.'/lib/dao');//dao类库目录
define('VIEW_PATH',APP_PATH.'/template');//视图目录
define("LOG_PATH",APP_PATH."/log");//日志目录
define("DEFAULT_ACTION_NAME","Index");//应用默认执行的action
define("DEFAULT_METHOD_NAME","index");//应用默认执行的方法
define("DEFAULT_TEMPLATE_NAME","index");//应用默认的模板文件名称
include(GALAVY_PATH.'/Galavy.php');//框架入口类
include(APP_PATH.'/config/config.php');//应用配置文件
Galavy::Run();
?>